security:
    encoders:
        App\Entity\User:
            algorithm: auto
        Symfony\Component\Security\Core\User\User:
            algorithm: auto

    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
        backend_users:
            memory:
                users:
                    admin1:
                        password: $2y$13$5Ygg9Lo/NHATLRADeB3nZ..5u.Ys9478emenxdJ4DQlCHJXXRjdPC
                        roles: 'ROLE_ADMIN'
              # used to reload user from session & other features (e.g. switch_user)
        users:
            entity:
                class: 'App\Entity\User'
                property: login

    firewalls:
        admin_protection:
            pattern: ^/admin/(.+)
            provider: backend_users
            http_basic: ~

        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: lazy
            guard:
                authenticators:
                    - App\Security\LoginFormAuthenticator
            provider: backend_users
            logout:
                path: app_logout

                # where to redirect after logout
                # target: app_any_route

            # activate different ways to authenticate
            # https://symfony.com/doc/current/security.html#firewalls-authentication

            # https://symfony.com/doc/current/security/impersonating_user.html
            # switch_user: true

    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
        - { path: ^/login$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/profile, roles: ROLE_USER }
